require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/**'

Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
