plugins: rubocop-rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }


AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'test/**'

Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
