require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HonorMembersController, :type => :controller do

  fixtures :users

  before do
    sign_in users[:admin] 
  end
  it "should have a current_user" do
    # note the fact that you should remove the "validate_session" parameter if this was a scaffold-generated controller
    subject.current_user.should_not be_nil
  end

  # This should return the minimal set of attributes required to create a valid
  # HonorMember. As you add validations to HonorMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {

    {
    :vorname=> "Vorname",
    :name => "Name" }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HonorMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all honor_members as @honor_members" do
      sign_in :admin
      honor_member = HonorMember.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:honor_members)).to eq([honor_member])
    end
  end

  describe "GET #show" do
    it "assigns the requested honor_member as @honor_member" do
      honor_member = HonorMember.create! valid_attributes
      get :show, {:id => honor_member.to_param}, valid_session
      expect(assigns(:honor_member)).to eq(honor_member)
    end
  end

  describe "GET #new" do
    it "assigns a new honor_member as @honor_member" do
      get :new, {}, valid_session
      expect(assigns(:honor_member)).to be_a_new(HonorMember)
    end
  end

  describe "GET #edit" do
    it "assigns the requested honor_member as @honor_member" do
      honor_member = HonorMember.create! valid_attributes
      get :edit, {:id => honor_member.to_param}, valid_session
      expect(assigns(:honor_member)).to eq(honor_member)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HonorMember" do
        expect {
          post :create, {:honor_member => valid_attributes}, valid_session
        }.to change(HonorMember, :count).by(1)
      end

      it "assigns a newly created honor_member as @honor_member" do
        post :create, {:honor_member => valid_attributes}, valid_session
        expect(assigns(:honor_member)).to be_a(HonorMember)
        expect(assigns(:honor_member)).to be_persisted
      end

      it "redirects to the created honor_member" do
        post :create, {:honor_member => valid_attributes}, valid_session
        expect(response).to redirect_to(HonorMember.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved honor_member as @honor_member" do
        post :create, {:honor_member => invalid_attributes}, valid_session
        expect(assigns(:honor_member)).to be_a_new(HonorMember)
      end

      it "re-renders the 'new' template" do
        post :create, {:honor_member => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          :name => "Changed Name"
        }
      }

      it "updates the requested honor_member" do
        honor_member = HonorMember.create! valid_attributes
        put :update, {:id => honor_member.to_param, :honor_member => new_attributes}, valid_session
        honor_member.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested honor_member as @honor_member" do
        honor_member = HonorMember.create! valid_attributes
        put :update, {:id => honor_member.to_param, :honor_member => valid_attributes}, valid_session
        expect(assigns(:honor_member)).to eq(honor_member)
      end

      it "redirects to the honor_member" do
        honor_member = HonorMember.create! valid_attributes
        put :update, {:id => honor_member.to_param, :honor_member => valid_attributes}, valid_session
        expect(response).to redirect_to(honor_member)
      end
    end

    context "with invalid params" do
      it "assigns the honor_member as @honor_member" do
        honor_member = HonorMember.create! valid_attributes
        put :update, {:id => honor_member.to_param, :honor_member => invalid_attributes}, valid_session
        expect(assigns(:honor_member)).to eq(honor_member)
      end

      it "re-renders the 'edit' template" do
        honor_member = HonorMember.create! valid_attributes
        put :update, {:id => honor_member.to_param, :honor_member => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested honor_member" do
      honor_member = HonorMember.create! valid_attributes
      expect {
        delete :destroy, {:id => honor_member.to_param}, valid_session
      }.to change(HonorMember, :count).by(-1)
    end

    it "redirects to the honor_members list" do
      honor_member = HonorMember.create! valid_attributes
      delete :destroy, {:id => honor_member.to_param}, valid_session
      expect(response).to redirect_to(honor_members_url)
    end
  end

  it "blocks unauthenticated access" do
    sign_in nil

    get :index

    expect(response).to redirect_to(new_user_session_path)
  end


end
