require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MagazineSamplingsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # MagazineSampling. As you add validations to MagazineSampling, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MagazineSamplingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all magazine_samplings as @magazine_samplings' do
      magazine_sampling = MagazineSampling.create! valid_attributes
      get :index
      expect(assigns(:magazine_samplings)).to eq([ magazine_sampling ])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested magazine_sampling as @magazine_sampling' do
      magazine_sampling = MagazineSampling.create! valid_attributes
      get :show, params: { id: magazine_sampling.to_param }
      expect(assigns(:magazine_sampling)).to eq(magazine_sampling)
    end
  end

  describe 'GET #new' do
    it 'assigns a new magazine_sampling as @magazine_sampling' do
      get :new
      expect(assigns(:magazine_sampling)).to be_a_new(MagazineSampling)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested magazine_sampling as @magazine_sampling' do
      magazine_sampling = MagazineSampling.create! valid_attributes
      get :edit, params: { id: magazine_sampling.to_param }
      expect(assigns(:magazine_sampling)).to eq(magazine_sampling)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new MagazineSampling' do
        expect do
          post :create, params: { magazine_sampling: valid_attributes }
        end.to change(MagazineSampling, :count).by(1)
      end

      it 'assigns a newly created magazine_sampling as @magazine_sampling' do
        post :create, params: { magazine_sampling: valid_attributes }
        expect(assigns(:magazine_sampling)).to be_a(MagazineSampling)
        expect(assigns(:magazine_sampling)).to be_persisted
      end

      it 'redirects to the created magazine_sampling' do
        post :create, params: { magazine_sampling: valid_attributes }
        expect(response).to redirect_to(MagazineSampling.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved magazine_sampling as @magazine_sampling' do
        post :create, params: { magazine_sampling: invalid_attributes }
        expect(assigns(:magazine_sampling)).to be_a_new(MagazineSampling)
      end

      it "re-renders the 'new' template" do
        post :create, params: { magazine_sampling: invalid_attributes }
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested magazine_sampling' do
        magazine_sampling = MagazineSampling.create! valid_attributes
        put :update, params: { id: magazine_sampling.to_param, magazine_sampling: new_attributes }
        magazine_sampling.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested magazine_sampling as @magazine_sampling' do
        magazine_sampling = MagazineSampling.create! valid_attributes
        put :update, params: { id: magazine_sampling.to_param, magazine_sampling: valid_attributes }
        expect(assigns(:magazine_sampling)).to eq(magazine_sampling)
      end

      it 'redirects to the magazine_sampling' do
        magazine_sampling = MagazineSampling.create! valid_attributes
        put :update, params: { id: magazine_sampling.to_param, magazine_sampling: valid_attributes }
        expect(response).to redirect_to(magazine_sampling)
      end
    end

    context 'with invalid params' do
      it 'assigns the magazine_sampling as @magazine_sampling' do
        magazine_sampling = MagazineSampling.create! valid_attributes
        put :update, params: { id: magazine_sampling.to_param, magazine_sampling: invalid_attributes }
        expect(assigns(:magazine_sampling)).to eq(magazine_sampling)
      end

      it "re-renders the 'edit' template" do
        magazine_sampling = MagazineSampling.create! valid_attributes
        put :update, params: { id: magazine_sampling.to_param, magazine_sampling: invalid_attributes }
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested magazine_sampling' do
      magazine_sampling = MagazineSampling.create! valid_attributes
      expect do
        delete :destroy, params: { id: magazine_sampling.to_param }
      end.to change(MagazineSampling, :count).by(-1)
    end

    it 'redirects to the magazine_samplings list' do
      magazine_sampling = MagazineSampling.create! valid_attributes
      delete :destroy, params: { id: magazine_sampling.to_param }
      expect(response).to redirect_to(magazine_samplings_url)
    end
  end
end
