require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MemberAccountBookingsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # MemberAccountBooking. As you add validations to MemberAccountBooking, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MemberAccountBookingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all member_account_bookings as @member_account_bookings' do
      member_account_booking = MemberAccountBooking.create! valid_attributes
      get :index
      expect(assigns(:member_account_bookings)).to eq([member_account_booking])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested member_account_booking as @member_account_booking' do
      member_account_booking = MemberAccountBooking.create! valid_attributes
      get :show, params: { id: member_account_booking.to_param }
      expect(assigns(:member_account_booking)).to eq(member_account_booking)
    end
  end

  describe 'GET #new' do
    it 'assigns a new member_account_booking as @member_account_booking' do
      get :new
      expect(assigns(:member_account_booking)).to be_a_new(MemberAccountBooking)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested member_account_booking as @member_account_booking' do
      member_account_booking = MemberAccountBooking.create! valid_attributes
      get :edit, params: { id: member_account_booking.to_param }
      expect(assigns(:member_account_booking)).to eq(member_account_booking)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new MemberAccountBooking' do
        expect do
          post :create, params: { member_account_booking: valid_attributes }
        end.to change(MemberAccountBooking, :count).by(1)
      end

      it 'assigns a newly created member_account_booking as @member_account_booking' do
        post :create, params: { member_account_booking: valid_attributes }
        expect(assigns(:member_account_booking)).to be_a(MemberAccountBooking)
        expect(assigns(:member_account_booking)).to be_persisted
      end

      it 'redirects to the created member_account_booking' do
        post :create, params: { member_account_booking: valid_attributes }
        expect(response).to redirect_to(MemberAccountBooking.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved member_account_booking as @member_account_booking' do
        post :create, params: { member_account_booking: invalid_attributes }
        expect(assigns(:member_account_booking)).to be_a_new(MemberAccountBooking)
      end

      it "re-renders the 'new' template" do
        post :create, params: { member_account_booking: invalid_attributes }
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested member_account_booking' do
        member_account_booking = MemberAccountBooking.create! valid_attributes
        put :update, params: { id: member_account_booking.to_param, member_account_booking: new_attributes }
        member_account_booking.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested member_account_booking as @member_account_booking' do
        member_account_booking = MemberAccountBooking.create! valid_attributes
        put :update, params: { id: member_account_booking.to_param, member_account_booking: valid_attributes }
        expect(assigns(:member_account_booking)).to eq(member_account_booking)
      end

      it 'redirects to the member_account_booking' do
        member_account_booking = MemberAccountBooking.create! valid_attributes
        put :update, params: { id: member_account_booking.to_param, member_account_booking: valid_attributes }
        expect(response).to redirect_to(member_account_booking)
      end
    end

    context 'with invalid params' do
      it 'assigns the member_account_booking as @member_account_booking' do
        member_account_booking = MemberAccountBooking.create! valid_attributes
        put :update, params: { id: member_account_booking.to_param, member_account_booking: invalid_attributes }
        expect(assigns(:member_account_booking)).to eq(member_account_booking)
      end

      it "re-renders the 'edit' template" do
        member_account_booking = MemberAccountBooking.create! valid_attributes
        put :update, params: { id: member_account_booking.to_param, member_account_booking: invalid_attributes }
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested member_account_booking' do
      member_account_booking = MemberAccountBooking.create! valid_attributes
      expect do
        delete :destroy, params: { id: member_account_booking.to_param }
      end.to change(MemberAccountBooking, :count).by(-1)
    end

    it 'redirects to the member_account_bookings list' do
      member_account_booking = MemberAccountBooking.create! valid_attributes
      delete :destroy, params: { id: member_account_booking.to_param }
      expect(response).to redirect_to(member_account_bookings_url)
    end
  end
end
