require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OrchestraContactsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # OrchestraContact. As you add validations to OrchestraContact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrchestraContactsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all orchestra_contacts as @orchestra_contacts" do
      orchestra_contact = OrchestraContact.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:orchestra_contacts)).to eq([orchestra_contact])
    end
  end

  describe "GET #show" do
    it "assigns the requested orchestra_contact as @orchestra_contact" do
      orchestra_contact = OrchestraContact.create! valid_attributes
      get :show, {:id => orchestra_contact.to_param}, valid_session
      expect(assigns(:orchestra_contact)).to eq(orchestra_contact)
    end
  end

  describe "GET #new" do
    it "assigns a new orchestra_contact as @orchestra_contact" do
      get :new, {}, valid_session
      expect(assigns(:orchestra_contact)).to be_a_new(OrchestraContact)
    end
  end

  describe "GET #edit" do
    it "assigns the requested orchestra_contact as @orchestra_contact" do
      orchestra_contact = OrchestraContact.create! valid_attributes
      get :edit, {:id => orchestra_contact.to_param}, valid_session
      expect(assigns(:orchestra_contact)).to eq(orchestra_contact)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OrchestraContact" do
        expect {
          post :create, {:orchestra_contact => valid_attributes}, valid_session
        }.to change(OrchestraContact, :count).by(1)
      end

      it "assigns a newly created orchestra_contact as @orchestra_contact" do
        post :create, {:orchestra_contact => valid_attributes}, valid_session
        expect(assigns(:orchestra_contact)).to be_a(OrchestraContact)
        expect(assigns(:orchestra_contact)).to be_persisted
      end

      it "redirects to the created orchestra_contact" do
        post :create, {:orchestra_contact => valid_attributes}, valid_session
        expect(response).to redirect_to(OrchestraContact.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved orchestra_contact as @orchestra_contact" do
        post :create, {:orchestra_contact => invalid_attributes}, valid_session
        expect(assigns(:orchestra_contact)).to be_a_new(OrchestraContact)
      end

      it "re-renders the 'new' template" do
        post :create, {:orchestra_contact => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orchestra_contact" do
        orchestra_contact = OrchestraContact.create! valid_attributes
        put :update, {:id => orchestra_contact.to_param, :orchestra_contact => new_attributes}, valid_session
        orchestra_contact.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested orchestra_contact as @orchestra_contact" do
        orchestra_contact = OrchestraContact.create! valid_attributes
        put :update, {:id => orchestra_contact.to_param, :orchestra_contact => valid_attributes}, valid_session
        expect(assigns(:orchestra_contact)).to eq(orchestra_contact)
      end

      it "redirects to the orchestra_contact" do
        orchestra_contact = OrchestraContact.create! valid_attributes
        put :update, {:id => orchestra_contact.to_param, :orchestra_contact => valid_attributes}, valid_session
        expect(response).to redirect_to(orchestra_contact)
      end
    end

    context "with invalid params" do
      it "assigns the orchestra_contact as @orchestra_contact" do
        orchestra_contact = OrchestraContact.create! valid_attributes
        put :update, {:id => orchestra_contact.to_param, :orchestra_contact => invalid_attributes}, valid_session
        expect(assigns(:orchestra_contact)).to eq(orchestra_contact)
      end

      it "re-renders the 'edit' template" do
        orchestra_contact = OrchestraContact.create! valid_attributes
        put :update, {:id => orchestra_contact.to_param, :orchestra_contact => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested orchestra_contact" do
      orchestra_contact = OrchestraContact.create! valid_attributes
      expect {
        delete :destroy, {:id => orchestra_contact.to_param}, valid_session
      }.to change(OrchestraContact, :count).by(-1)
    end

    it "redirects to the orchestra_contacts list" do
      orchestra_contact = OrchestraContact.create! valid_attributes
      delete :destroy, {:id => orchestra_contact.to_param}, valid_session
      expect(response).to redirect_to(orchestra_contacts_url)
    end
  end

end
