require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RegionalOrganizationBookingsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # RegionalOrganizationBooking. As you add validations to RegionalOrganizationBooking, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegionalOrganizationBookingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all regional_organization_bookings as @regional_organization_bookings" do
      regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
      get :index, {}
      expect(assigns(:regional_organization_bookings)).to eq([regional_organization_booking])
    end
  end

  describe "GET #show" do
    it "assigns the requested regional_organization_booking as @regional_organization_booking" do
      regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
      get :show, {:id => regional_organization_booking.to_param}
      expect(assigns(:regional_organization_booking)).to eq(regional_organization_booking)
    end
  end

  describe "GET #new" do
    it "assigns a new regional_organization_booking as @regional_organization_booking" do
      get :new, {}
      expect(assigns(:regional_organization_booking)).to be_a_new(RegionalOrganizationBooking)
    end
  end

  describe "GET #edit" do
    it "assigns the requested regional_organization_booking as @regional_organization_booking" do
      regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
      get :edit, {:id => regional_organization_booking.to_param}
      expect(assigns(:regional_organization_booking)).to eq(regional_organization_booking)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RegionalOrganizationBooking" do
        expect {
          post :create, {:regional_organization_booking => valid_attributes}
        }.to change(RegionalOrganizationBooking, :count).by(1)
      end

      it "assigns a newly created regional_organization_booking as @regional_organization_booking" do
        post :create, {:regional_organization_booking => valid_attributes}
        expect(assigns(:regional_organization_booking)).to be_a(RegionalOrganizationBooking)
        expect(assigns(:regional_organization_booking)).to be_persisted
      end

      it "redirects to the created regional_organization_booking" do
        post :create, {:regional_organization_booking => valid_attributes}
        expect(response).to redirect_to(RegionalOrganizationBooking.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved regional_organization_booking as @regional_organization_booking" do
        post :create, {:regional_organization_booking => invalid_attributes}
        expect(assigns(:regional_organization_booking)).to be_a_new(RegionalOrganizationBooking)
      end

      it "re-renders the 'new' template" do
        post :create, {:regional_organization_booking => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested regional_organization_booking" do
        regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
        put :update, {:id => regional_organization_booking.to_param, :regional_organization_booking => new_attributes}
        regional_organization_booking.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested regional_organization_booking as @regional_organization_booking" do
        regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
        put :update, {:id => regional_organization_booking.to_param, :regional_organization_booking => valid_attributes}
        expect(assigns(:regional_organization_booking)).to eq(regional_organization_booking)
      end

      it "redirects to the regional_organization_booking" do
        regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
        put :update, {:id => regional_organization_booking.to_param, :regional_organization_booking => valid_attributes}
        expect(response).to redirect_to(regional_organization_booking)
      end
    end

    context "with invalid params" do
      it "assigns the regional_organization_booking as @regional_organization_booking" do
        regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
        put :update, {:id => regional_organization_booking.to_param, :regional_organization_booking => invalid_attributes}
        expect(assigns(:regional_organization_booking)).to eq(regional_organization_booking)
      end

      it "re-renders the 'edit' template" do
        regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
        put :update, {:id => regional_organization_booking.to_param, :regional_organization_booking => invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested regional_organization_booking" do
      regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
      expect {
        delete :destroy, {:id => regional_organization_booking.to_param}
      }.to change(RegionalOrganizationBooking, :count).by(-1)
    end

    it "redirects to the regional_organization_bookings list" do
      regional_organization_booking = RegionalOrganizationBooking.create! valid_attributes
      delete :destroy, {:id => regional_organization_booking.to_param}
      expect(response).to redirect_to(regional_organization_bookings_url)
    end
  end

end
