require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReportSheetsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # ReportSheet. As you add validations to ReportSheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportSheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all report_sheets as @report_sheets' do
      report_sheet = ReportSheet.create! valid_attributes
      get :index
      expect(assigns(:report_sheets)).to eq([report_sheet])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested report_sheet as @report_sheet' do
      report_sheet = ReportSheet.create! valid_attributes
      get :show, params: { id: report_sheet.to_param }
      expect(assigns(:report_sheet)).to eq(report_sheet)
    end
  end

  describe 'GET #new' do
    it 'assigns a new report_sheet as @report_sheet' do
      get :new
      expect(assigns(:report_sheet)).to be_a_new(ReportSheet)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested report_sheet as @report_sheet' do
      report_sheet = ReportSheet.create! valid_attributes
      get :edit, params: { id: report_sheet.to_param }
      expect(assigns(:report_sheet)).to eq(report_sheet)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new ReportSheet' do
        expect do
          post :create, params: { report_sheet: valid_attributes }
        end.to change(ReportSheet, :count).by(1)
      end

      it 'assigns a newly created report_sheet as @report_sheet' do
        post :create, params: { report_sheet: valid_attributes }
        expect(assigns(:report_sheet)).to be_a(ReportSheet)
        expect(assigns(:report_sheet)).to be_persisted
      end

      it 'redirects to the created report_sheet' do
        post :create, params: { report_sheet: valid_attributes }
        expect(response).to redirect_to(ReportSheet.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved report_sheet as @report_sheet' do
        post :create, params: { report_sheet: invalid_attributes }
        expect(assigns(:report_sheet)).to be_a_new(ReportSheet)
      end

      it "re-renders the 'new' template" do
        post :create, params: { report_sheet: invalid_attributes }
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested report_sheet' do
        report_sheet = ReportSheet.create! valid_attributes
        put :update, params: { id: report_sheet.to_param, report_sheet: new_attributes }
        report_sheet.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested report_sheet as @report_sheet' do
        report_sheet = ReportSheet.create! valid_attributes
        put :update, params: { id: report_sheet.to_param, report_sheet: valid_attributes }
        expect(assigns(:report_sheet)).to eq(report_sheet)
      end

      it 'redirects to the report_sheet' do
        report_sheet = ReportSheet.create! valid_attributes
        put :update, params: { id: report_sheet.to_param, report_sheet: valid_attributes }
        expect(response).to redirect_to(report_sheet)
      end
    end

    context 'with invalid params' do
      it 'assigns the report_sheet as @report_sheet' do
        report_sheet = ReportSheet.create! valid_attributes
        put :update, params: { id: report_sheet.to_param, report_sheet: invalid_attributes }
        expect(assigns(:report_sheet)).to eq(report_sheet)
      end

      it "re-renders the 'edit' template" do
        report_sheet = ReportSheet.create! valid_attributes
        put :update, params: { id: report_sheet.to_param, report_sheet: invalid_attributes }
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested report_sheet' do
      report_sheet = ReportSheet.create! valid_attributes
      expect do
        delete :destroy, params: { id: report_sheet.to_param }
      end.to change(ReportSheet, :count).by(-1)
    end

    it 'redirects to the report_sheets list' do
      report_sheet = ReportSheet.create! valid_attributes
      delete :destroy, params: { id: report_sheet.to_param }
      expect(response).to redirect_to(report_sheets_url)
    end
  end
end
