require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UrlCategoriesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # UrlCategory. As you add validations to UrlCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UrlCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all url_categories as @url_categories' do
      url_category = UrlCategory.create! valid_attributes
      get :index
      expect(assigns(:url_categories)).to eq([ url_category ])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested url_category as @url_category' do
      url_category = UrlCategory.create! valid_attributes
      get :show, params: { id: url_category.to_param }
      expect(assigns(:url_category)).to eq(url_category)
    end
  end

  describe 'GET #new' do
    it 'assigns a new url_category as @url_category' do
      get :new
      expect(assigns(:url_category)).to be_a_new(UrlCategory)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested url_category as @url_category' do
      url_category = UrlCategory.create! valid_attributes
      get :edit, params: { id: url_category.to_param }
      expect(assigns(:url_category)).to eq(url_category)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new UrlCategory' do
        expect do
          post :create, params: { url_category: valid_attributes }
        end.to change(UrlCategory, :count).by(1)
      end

      it 'assigns a newly created url_category as @url_category' do
        post :create, params: { url_category: valid_attributes }
        expect(assigns(:url_category)).to be_a(UrlCategory)
        expect(assigns(:url_category)).to be_persisted
      end

      it 'redirects to the created url_category' do
        post :create, params: { url_category: valid_attributes }
        expect(response).to redirect_to(UrlCategory.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved url_category as @url_category' do
        post :create, params: { url_category: invalid_attributes }
        expect(assigns(:url_category)).to be_a_new(UrlCategory)
      end

      it "re-renders the 'new' template" do
        post :create, params: { url_category: invalid_attributes }
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested url_category' do
        url_category = UrlCategory.create! valid_attributes
        put :update, params: { id: url_category.to_param, url_category: new_attributes }
        url_category.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested url_category as @url_category' do
        url_category = UrlCategory.create! valid_attributes
        put :update, params: { id: url_category.to_param, url_category: valid_attributes }
        expect(assigns(:url_category)).to eq(url_category)
      end

      it 'redirects to the url_category' do
        url_category = UrlCategory.create! valid_attributes
        put :update, params: { id: url_category.to_param, url_category: valid_attributes }
        expect(response).to redirect_to(url_category)
      end
    end

    context 'with invalid params' do
      it 'assigns the url_category as @url_category' do
        url_category = UrlCategory.create! valid_attributes
        put :update, params: { id: url_category.to_param, url_category: invalid_attributes }
        expect(assigns(:url_category)).to eq(url_category)
      end

      it "re-renders the 'edit' template" do
        url_category = UrlCategory.create! valid_attributes
        put :update, params: { id: url_category.to_param, url_category: invalid_attributes }
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested url_category' do
      url_category = UrlCategory.create! valid_attributes
      expect do
        delete :destroy, params: { id: url_category.to_param }
      end.to change(UrlCategory, :count).by(-1)
    end

    it 'redirects to the url_categories list' do
      url_category = UrlCategory.create! valid_attributes
      delete :destroy, params: { id: url_category.to_param }
      expect(response).to redirect_to(url_categories_url)
    end
  end
end
